// Generated by CIRCT unknown git version

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module Arty100THarness(	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:314:9]
  input         sys_clock,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  output [13:0] ddr_ddr3_addr,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  output [2:0]  ddr_ddr3_ba,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  output        ddr_ddr3_ras_n,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  output        ddr_ddr3_cas_n,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  output        ddr_ddr3_we_n,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  output        ddr_ddr3_reset_n,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  output        ddr_ddr3_ck_p,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  output        ddr_ddr3_ck_n,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  output        ddr_ddr3_cke,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  output        ddr_ddr3_cs_n,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  output [1:0]  ddr_ddr3_dm,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  output        ddr_ddr3_odt,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  inout  [15:0] ddr_ddr3_dq,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  inout  [1:0]  ddr_ddr3_dqs_n,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  inout  [1:0]  ddr_ddr3_dqs_p,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  output        led_0,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  output        led_1,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  output        led_2,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  output        led_3,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  output        led_4,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  output        led_5,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  output        led_6,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  output        led_7,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  output        led_8,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  output        led_9,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  output        led_10,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  output        led_11,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  output        led_12,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  output        led_13,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  output        led_14,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  output        led_15,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  input         reset,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:317:19]
  output        uart_txd,	// @[fpga/src/main/scala/arty100t/HarnessBinders.scala:110:23]
  input         uart_rxd,	// @[fpga/src/main/scala/arty100t/HarnessBinders.scala:110:23]
  input         jtag_TCK,	// @[fpga/src/main/scala/arty100t/HarnessBinders.scala:129:23]
  input         jtag_TMS,	// @[fpga/src/main/scala/arty100t/HarnessBinders.scala:129:23]
  input         jtag_TDI,	// @[fpga/src/main/scala/arty100t/HarnessBinders.scala:129:23]
  output        jtag_TDO,	// @[fpga/src/main/scala/arty100t/HarnessBinders.scala:129:23]
  output        uart_tsi_txd,	// @[fpga/src/main/scala/arty100t/HarnessBinders.scala:25:23]
  input         uart_tsi_rxd	// @[fpga/src/main/scala/arty100t/HarnessBinders.scala:25:23]
);

  wire        _harnessBinderReset_catcher_io_sync_reset;	// @[generators/rocket-chip/src/main/scala/util/ResetCatchAndSync.scala:39:28]
  wire        _plusarg_reader_out;	// @[generators/rocket-chip/src/main/scala/util/PlusArg.scala:80:11]
  wire        _chiptop0_tl_slave_0_a_valid;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:100:40]
  wire [2:0]  _chiptop0_tl_slave_0_a_bits_opcode;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:100:40]
  wire [2:0]  _chiptop0_tl_slave_0_a_bits_param;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:100:40]
  wire [2:0]  _chiptop0_tl_slave_0_a_bits_size;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:100:40]
  wire [3:0]  _chiptop0_tl_slave_0_a_bits_source;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:100:40]
  wire [31:0] _chiptop0_tl_slave_0_a_bits_address;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:100:40]
  wire [7:0]  _chiptop0_tl_slave_0_a_bits_mask;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:100:40]
  wire [63:0] _chiptop0_tl_slave_0_a_bits_data;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:100:40]
  wire        _chiptop0_tl_slave_0_a_bits_corrupt;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:100:40]
  wire        _chiptop0_tl_slave_0_d_ready;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:100:40]
  wire [3:0]  _chiptop0_uart_tsi_tsi2tl_state;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:100:40]
  wire        _powerOnReset_fpga_power_on_power_on_reset;	// @[fpga/fpga-shells/src/main/scala/ip/xilinx/Xilinx.scala:103:21]
  wire        _reset_ibuf_O;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:320:28]
  wire        _sys_clock_ibufg_O;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ClockOverlay.scala:32:22]
  wire        _harnessSysPLLNode_clk_out1;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/XilinxShell.scala:76:55]
  wire        _harnessSysPLLNode_clk_out2;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/XilinxShell.scala:76:55]
  wire        _harnessSysPLLNode_clk_out3;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/XilinxShell.scala:76:55]
  wire        _harnessSysPLLNode_locked;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/XilinxShell.scala:76:55]
  wire        _mig_auto_buffer_in_a_ready;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:239:23]
  wire        _mig_auto_buffer_in_d_valid;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:239:23]
  wire [2:0]  _mig_auto_buffer_in_d_bits_opcode;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:239:23]
  wire [1:0]  _mig_auto_buffer_in_d_bits_param;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:239:23]
  wire [2:0]  _mig_auto_buffer_in_d_bits_size;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:239:23]
  wire [3:0]  _mig_auto_buffer_in_d_bits_source;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:239:23]
  wire        _mig_auto_buffer_in_d_bits_sink;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:239:23]
  wire        _mig_auto_buffer_in_d_bits_denied;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:239:23]
  wire [63:0] _mig_auto_buffer_in_d_bits_data;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:239:23]
  wire        _mig_auto_buffer_in_d_bits_corrupt;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:239:23]
  wire        _mig_io_port_ui_clk;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:239:23]
  wire        _mig_io_port_ui_clk_sync_rst;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:239:23]
  wire        _mig_io_port_mmcm_locked;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:239:23]
  wire        _mig_io_port_init_calib_complete;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:239:23]
  wire        _ddrGroup_auto_out_1_clock;	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:37:69]
  wire        _ddrGroup_auto_out_1_reset;	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:37:69]
  wire        _ddrGroup_auto_out_0_clock;	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:37:69]
  wire        _ddrGroup_auto_out_0_reset;	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:37:69]
  wire        _dutWrangler_auto_out_3_reset;	// @[fpga/src/main/scala/arty100t/Harness.scala:30:31]
  wire        _dutWrangler_auto_out_2_clock;	// @[fpga/src/main/scala/arty100t/Harness.scala:30:31]
  wire        _dutWrangler_auto_out_1_clock;	// @[fpga/src/main/scala/arty100t/Harness.scala:30:31]
  wire        _dutWrangler_auto_out_0_clock;	// @[fpga/src/main/scala/arty100t/Harness.scala:30:31]
  wire        _dutWrangler_auto_out_0_reset;	// @[fpga/src/main/scala/arty100t/Harness.scala:30:31]
  reg  [1:0]  ddrBlockDuringReset_nodeOut_a_c_value;	// @[src/main/scala/chisel3/util/Counter.scala:61:40]
  reg         ddrBlockDuringReset_nodeOut_a_r;	// @[generators/rocket-chip/src/main/scala/util/BlockDuringReset.scala:13:24]
  reg  [1:0]  ddrBlockDuringReset_nodeIn_d_c_value;	// @[src/main/scala/chisel3/util/Counter.scala:61:40]
  reg         ddrBlockDuringReset_nodeIn_d_r;	// @[generators/rocket-chip/src/main/scala/util/BlockDuringReset.scala:13:24]
  wire        mig_io_port_sys_rst = ~_reset_ibuf_O | _powerOnReset_fpga_power_on_power_on_reset;	// @[fpga/fpga-shells/src/main/scala/ip/xilinx/Xilinx.scala:103:21, fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:320:28, :331:{8,26}]
  reg  [25:0] REG;	// @[fpga/src/main/scala/arty100t/Harness.scala:61:28]
  reg  [1:0]  REG_1;	// @[fpga/src/main/scala/arty100t/Harness.scala:62:23]
  wire        _GEN = REG_1 == 2'h2;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:314:9, fpga/src/main/scala/arty100t/Harness.scala:62:23, :63:60]
  always @(posedge _dutWrangler_auto_out_0_clock) begin	// @[fpga/src/main/scala/arty100t/Harness.scala:30:31]
    if (_harnessBinderReset_catcher_io_sync_reset | ~_mig_io_port_init_calib_complete) begin	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:239:23, fpga/src/main/scala/arty100t/Harness.scala:30:31, :85:{67,70}, generators/rocket-chip/src/main/scala/util/ResetCatchAndSync.scala:39:28]
      ddrBlockDuringReset_nodeOut_a_c_value <= 2'h0;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:314:9, src/main/scala/chisel3/util/Counter.scala:61:40]
      ddrBlockDuringReset_nodeOut_a_r <= 1'h0;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:314:9, generators/rocket-chip/src/main/scala/util/BlockDuringReset.scala:13:24]
      ddrBlockDuringReset_nodeIn_d_c_value <= 2'h0;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:314:9, src/main/scala/chisel3/util/Counter.scala:61:40]
      ddrBlockDuringReset_nodeIn_d_r <= 1'h0;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:314:9, generators/rocket-chip/src/main/scala/util/BlockDuringReset.scala:13:24]
    end
    else begin	// @[fpga/src/main/scala/arty100t/Harness.scala:30:31]
      ddrBlockDuringReset_nodeOut_a_c_value <= ddrBlockDuringReset_nodeOut_a_c_value + 2'h1;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:314:9, src/main/scala/chisel3/util/Counter.scala:61:40, :77:24]
      ddrBlockDuringReset_nodeOut_a_r <= (&ddrBlockDuringReset_nodeOut_a_c_value) | ddrBlockDuringReset_nodeOut_a_r;	// @[generators/rocket-chip/src/main/scala/util/BlockDuringReset.scala:13:24, src/main/scala/chisel3/util/Counter.scala:61:40, :73:24]
      ddrBlockDuringReset_nodeIn_d_c_value <= ddrBlockDuringReset_nodeIn_d_c_value + 2'h1;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:314:9, src/main/scala/chisel3/util/Counter.scala:61:40, :77:24]
      ddrBlockDuringReset_nodeIn_d_r <= (&ddrBlockDuringReset_nodeIn_d_c_value) | ddrBlockDuringReset_nodeIn_d_r;	// @[generators/rocket-chip/src/main/scala/util/BlockDuringReset.scala:13:24, src/main/scala/chisel3/util/Counter.scala:61:40, :73:24]
    end
  end // always @(posedge)
  always @(posedge _sys_clock_ibufg_O) begin	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ClockOverlay.scala:32:22]
    if (_dutWrangler_auto_out_0_reset) begin	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ClockOverlay.scala:32:22, fpga/src/main/scala/arty100t/Harness.scala:30:31]
      REG <= 26'h0;	// @[fpga/src/main/scala/arty100t/Harness.scala:61:28]
      REG_1 <= 2'h0;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:314:9, fpga/src/main/scala/arty100t/Harness.scala:62:23]
    end
    else begin	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ClockOverlay.scala:32:22]
      REG <= REG == 26'h2155554 ? 26'h0 : REG + 26'h1;	// @[fpga/src/main/scala/arty100t/Harness.scala:61:28, :64:{21,30,61}]
      if (REG == 26'h0)	// @[fpga/src/main/scala/arty100t/Harness.scala:61:28, :65:21]
        REG_1 <= _GEN ? 2'h0 : REG_1 + 2'h1;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:314:9, fpga/src/main/scala/arty100t/Harness.scala:62:23, :63:60, :66:{18,58}]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:314:9]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:314:9]
      `FIRRTL_BEFORE_INITIAL	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:314:9]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:1];	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:314:9]
    initial begin	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:314:9]
      `ifdef INIT_RANDOM_PROLOG_	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:314:9]
        `INIT_RANDOM_PROLOG_	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:314:9]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:314:9]
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          _RANDOM[i[0]] = `RANDOM;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:314:9]
        end	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:314:9]
        ddrBlockDuringReset_nodeOut_a_c_value = _RANDOM[1'h0][1:0];	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:314:9, src/main/scala/chisel3/util/Counter.scala:61:40]
        ddrBlockDuringReset_nodeOut_a_r = _RANDOM[1'h0][2];	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:314:9, generators/rocket-chip/src/main/scala/util/BlockDuringReset.scala:13:24, src/main/scala/chisel3/util/Counter.scala:61:40]
        ddrBlockDuringReset_nodeIn_d_c_value = _RANDOM[1'h0][4:3];	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:314:9, src/main/scala/chisel3/util/Counter.scala:61:40]
        ddrBlockDuringReset_nodeIn_d_r = _RANDOM[1'h0][5];	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:314:9, generators/rocket-chip/src/main/scala/util/BlockDuringReset.scala:13:24, src/main/scala/chisel3/util/Counter.scala:61:40]
        REG = _RANDOM[1'h0][31:6];	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:314:9, fpga/src/main/scala/arty100t/Harness.scala:61:28, src/main/scala/chisel3/util/Counter.scala:61:40]
        REG_1 = _RANDOM[1'h1][1:0];	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:314:9, fpga/src/main/scala/arty100t/Harness.scala:62:23]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:314:9]
      `FIRRTL_AFTER_INITIAL	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:314:9]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  ResetWrangler dutWrangler (	// @[fpga/src/main/scala/arty100t/Harness.scala:30:31]
    .auto_in_3_clock  (_mig_io_port_ui_clk),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:239:23]
    .auto_in_3_reset  (~_mig_io_port_mmcm_locked | _mig_io_port_ui_clk_sync_rst),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:239:23, :258:{17,35}]
    .auto_in_2_clock  (_ddrGroup_auto_out_1_clock),	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:37:69]
    .auto_in_2_reset  (_ddrGroup_auto_out_1_reset),	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:37:69]
    .auto_in_1_clock  (_ddrGroup_auto_out_0_clock),	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:37:69]
    .auto_in_1_reset  (_ddrGroup_auto_out_0_reset),	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:37:69]
    .auto_in_0_clock  (_harnessSysPLLNode_clk_out1),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/XilinxShell.scala:76:55]
    .auto_in_0_reset  (~_harnessSysPLLNode_locked | ~_reset_ibuf_O),	// @[fpga/fpga-shells/src/main/scala/clocks/PLLFactory.scala:78:{20,35}, fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:320:28, fpga/fpga-shells/src/main/scala/shell/xilinx/XilinxShell.scala:76:55, fpga/src/main/scala/arty100t/Harness.scala:54:56]
    .auto_out_3_reset (_dutWrangler_auto_out_3_reset),
    .auto_out_2_clock (_dutWrangler_auto_out_2_clock),
    .auto_out_1_clock (_dutWrangler_auto_out_1_clock),
    .auto_out_0_clock (_dutWrangler_auto_out_0_clock),
    .auto_out_0_reset (_dutWrangler_auto_out_0_reset)
  );	// @[fpga/src/main/scala/arty100t/Harness.scala:30:31]
  ClockGroup_1 ddrGroup (	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:37:69]
    .auto_in_member_ddrGroup_1_clock (_harnessSysPLLNode_clk_out3),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/XilinxShell.scala:76:55]
    .auto_in_member_ddrGroup_1_reset (~_harnessSysPLLNode_locked | ~_reset_ibuf_O),	// @[fpga/fpga-shells/src/main/scala/clocks/PLLFactory.scala:78:{20,35}, fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:320:28, fpga/fpga-shells/src/main/scala/shell/xilinx/XilinxShell.scala:76:55, fpga/src/main/scala/arty100t/Harness.scala:54:56]
    .auto_in_member_ddrGroup_0_clock (_harnessSysPLLNode_clk_out2),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/XilinxShell.scala:76:55]
    .auto_in_member_ddrGroup_0_reset (~_harnessSysPLLNode_locked | ~_reset_ibuf_O),	// @[fpga/fpga-shells/src/main/scala/clocks/PLLFactory.scala:78:{20,35}, fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:320:28, fpga/fpga-shells/src/main/scala/shell/xilinx/XilinxShell.scala:76:55, fpga/src/main/scala/arty100t/Harness.scala:54:56]
    .auto_out_1_clock                (_ddrGroup_auto_out_1_clock),
    .auto_out_1_reset                (_ddrGroup_auto_out_1_reset),
    .auto_out_0_clock                (_ddrGroup_auto_out_0_clock),
    .auto_out_0_reset                (_ddrGroup_auto_out_0_reset)
  );	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:37:69]
  XilinxArty100TMIG mig (	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:239:23]
    .clock                         (_dutWrangler_auto_out_0_clock),	// @[fpga/src/main/scala/arty100t/Harness.scala:30:31]
    .reset                         (_harnessBinderReset_catcher_io_sync_reset),	// @[generators/rocket-chip/src/main/scala/util/ResetCatchAndSync.scala:39:28]
    .auto_buffer_in_a_ready        (_mig_auto_buffer_in_a_ready),
    .auto_buffer_in_a_valid        (ddrBlockDuringReset_nodeOut_a_r & _chiptop0_tl_slave_0_a_valid),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:100:40, generators/rocket-chip/src/main/scala/util/BlockDuringReset.scala:13:24, generators/rocket-chip/src/main/scala/util/Blockable.scala:35:18, :38:30, :39:20]
    .auto_buffer_in_a_bits_opcode  (_chiptop0_tl_slave_0_a_bits_opcode),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:100:40]
    .auto_buffer_in_a_bits_param   (_chiptop0_tl_slave_0_a_bits_param),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:100:40]
    .auto_buffer_in_a_bits_size    (_chiptop0_tl_slave_0_a_bits_size),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:100:40]
    .auto_buffer_in_a_bits_source  (_chiptop0_tl_slave_0_a_bits_source),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:100:40]
    .auto_buffer_in_a_bits_address (_chiptop0_tl_slave_0_a_bits_address),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:100:40]
    .auto_buffer_in_a_bits_mask    (_chiptop0_tl_slave_0_a_bits_mask),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:100:40]
    .auto_buffer_in_a_bits_data    (_chiptop0_tl_slave_0_a_bits_data),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:100:40]
    .auto_buffer_in_a_bits_corrupt (_chiptop0_tl_slave_0_a_bits_corrupt),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:100:40]
    .auto_buffer_in_d_ready        (ddrBlockDuringReset_nodeIn_d_r & _chiptop0_tl_slave_0_d_ready),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:100:40, generators/rocket-chip/src/main/scala/util/BlockDuringReset.scala:13:24, generators/rocket-chip/src/main/scala/util/Blockable.scala:36:18, :38:30, :40:20]
    .auto_buffer_in_d_valid        (_mig_auto_buffer_in_d_valid),
    .auto_buffer_in_d_bits_opcode  (_mig_auto_buffer_in_d_bits_opcode),
    .auto_buffer_in_d_bits_param   (_mig_auto_buffer_in_d_bits_param),
    .auto_buffer_in_d_bits_size    (_mig_auto_buffer_in_d_bits_size),
    .auto_buffer_in_d_bits_source  (_mig_auto_buffer_in_d_bits_source),
    .auto_buffer_in_d_bits_sink    (_mig_auto_buffer_in_d_bits_sink),
    .auto_buffer_in_d_bits_denied  (_mig_auto_buffer_in_d_bits_denied),
    .auto_buffer_in_d_bits_data    (_mig_auto_buffer_in_d_bits_data),
    .auto_buffer_in_d_bits_corrupt (_mig_auto_buffer_in_d_bits_corrupt),
    .io_port_ddr3_addr             (ddr_ddr3_addr),
    .io_port_ddr3_ba               (ddr_ddr3_ba),
    .io_port_ddr3_ras_n            (ddr_ddr3_ras_n),
    .io_port_ddr3_cas_n            (ddr_ddr3_cas_n),
    .io_port_ddr3_we_n             (ddr_ddr3_we_n),
    .io_port_ddr3_reset_n          (ddr_ddr3_reset_n),
    .io_port_ddr3_ck_p             (ddr_ddr3_ck_p),
    .io_port_ddr3_ck_n             (ddr_ddr3_ck_n),
    .io_port_ddr3_cke              (ddr_ddr3_cke),
    .io_port_ddr3_cs_n             (ddr_ddr3_cs_n),
    .io_port_ddr3_dm               (ddr_ddr3_dm),
    .io_port_ddr3_odt              (ddr_ddr3_odt),
    .io_port_ddr3_dq               (ddr_ddr3_dq),
    .io_port_ddr3_dqs_n            (ddr_ddr3_dqs_n),
    .io_port_ddr3_dqs_p            (ddr_ddr3_dqs_p),
    .io_port_sys_clk_i             (_dutWrangler_auto_out_1_clock),	// @[fpga/src/main/scala/arty100t/Harness.scala:30:31]
    .io_port_clk_ref_i             (_dutWrangler_auto_out_2_clock),	// @[fpga/src/main/scala/arty100t/Harness.scala:30:31]
    .io_port_ui_clk                (_mig_io_port_ui_clk),
    .io_port_ui_clk_sync_rst       (_mig_io_port_ui_clk_sync_rst),
    .io_port_mmcm_locked           (_mig_io_port_mmcm_locked),
    .io_port_aresetn               (~_dutWrangler_auto_out_3_reset),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:262:21, fpga/src/main/scala/arty100t/Harness.scala:30:31]
    .io_port_init_calib_complete   (_mig_io_port_init_calib_complete),
    .io_port_sys_rst               (mig_io_port_sys_rst)	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:331:26]
  );	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:239:23]
  harnessSysPLLNode harnessSysPLLNode (	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/XilinxShell.scala:76:55]
    .clk_in1  (_sys_clock_ibufg_O),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ClockOverlay.scala:32:22]
    .clk_out1 (_harnessSysPLLNode_clk_out1),
    .clk_out2 (_harnessSysPLLNode_clk_out2),
    .clk_out3 (_harnessSysPLLNode_clk_out3),
    .reset    (mig_io_port_sys_rst),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:331:26]
    .locked   (_harnessSysPLLNode_locked)
  );	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/XilinxShell.scala:76:55]
  IBUFG sys_clock_ibufg (	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ClockOverlay.scala:32:22]
    .O (_sys_clock_ibufg_O),
    .I (sys_clock)
  );	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ClockOverlay.scala:32:22]
  IBUF reset_ibuf (	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:320:28]
    .O (_reset_ibuf_O),
    .I (reset)
  );	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:320:28]
  PowerOnResetFPGAOnly powerOnReset_fpga_power_on (	// @[fpga/fpga-shells/src/main/scala/ip/xilinx/Xilinx.scala:103:21]
    .clock          (_sys_clock_ibufg_O),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ClockOverlay.scala:32:22]
    .power_on_reset (_powerOnReset_fpga_power_on_power_on_reset)
  );	// @[fpga/fpga-shells/src/main/scala/ip/xilinx/Xilinx.scala:103:21]
  ChipTop chiptop0 (	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:100:40]
    .uart_0_txd                (uart_txd),
    .uart_0_rxd                (uart_rxd),
    .tl_slave_0_a_ready        (ddrBlockDuringReset_nodeOut_a_r & _mig_auto_buffer_in_a_ready),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:239:23, generators/rocket-chip/src/main/scala/util/BlockDuringReset.scala:13:24, generators/rocket-chip/src/main/scala/util/Blockable.scala:36:18, :38:30, :40:20]
    .tl_slave_0_a_valid        (_chiptop0_tl_slave_0_a_valid),
    .tl_slave_0_a_bits_opcode  (_chiptop0_tl_slave_0_a_bits_opcode),
    .tl_slave_0_a_bits_param   (_chiptop0_tl_slave_0_a_bits_param),
    .tl_slave_0_a_bits_size    (_chiptop0_tl_slave_0_a_bits_size),
    .tl_slave_0_a_bits_source  (_chiptop0_tl_slave_0_a_bits_source),
    .tl_slave_0_a_bits_address (_chiptop0_tl_slave_0_a_bits_address),
    .tl_slave_0_a_bits_mask    (_chiptop0_tl_slave_0_a_bits_mask),
    .tl_slave_0_a_bits_data    (_chiptop0_tl_slave_0_a_bits_data),
    .tl_slave_0_a_bits_corrupt (_chiptop0_tl_slave_0_a_bits_corrupt),
    .tl_slave_0_d_ready        (_chiptop0_tl_slave_0_d_ready),
    .tl_slave_0_d_valid        (ddrBlockDuringReset_nodeIn_d_r & _mig_auto_buffer_in_d_valid),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:239:23, generators/rocket-chip/src/main/scala/util/BlockDuringReset.scala:13:24, generators/rocket-chip/src/main/scala/util/Blockable.scala:35:18, :38:30, :39:20]
    .tl_slave_0_d_bits_opcode  (_mig_auto_buffer_in_d_bits_opcode),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:239:23]
    .tl_slave_0_d_bits_param   (_mig_auto_buffer_in_d_bits_param),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:239:23]
    .tl_slave_0_d_bits_size    (_mig_auto_buffer_in_d_bits_size),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:239:23]
    .tl_slave_0_d_bits_source  (_mig_auto_buffer_in_d_bits_source),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:239:23]
    .tl_slave_0_d_bits_sink    (_mig_auto_buffer_in_d_bits_sink),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:239:23]
    .tl_slave_0_d_bits_denied  (_mig_auto_buffer_in_d_bits_denied),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:239:23]
    .tl_slave_0_d_bits_data    (_mig_auto_buffer_in_d_bits_data),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:239:23]
    .tl_slave_0_d_bits_corrupt (_mig_auto_buffer_in_d_bits_corrupt),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:239:23]
    .custom_boot               (_plusarg_reader_out),	// @[generators/rocket-chip/src/main/scala/util/PlusArg.scala:80:11]
    .jtag_TCK                  (jtag_TCK),
    .jtag_TMS                  (jtag_TMS),
    .jtag_TDI                  (jtag_TDI),
    .jtag_TDO                  (jtag_TDO),
    .jtag_reset                (_dutWrangler_auto_out_0_reset),	// @[fpga/src/main/scala/arty100t/Harness.scala:30:31]
    .uart_tsi_uart_txd         (uart_tsi_txd),
    .uart_tsi_uart_rxd         (uart_tsi_rxd),
    .uart_tsi_dropped          (led_4),
    .uart_tsi_tsi2tl_state     (_chiptop0_uart_tsi_tsi2tl_state),
    .reset_io                  (_dutWrangler_auto_out_0_reset),	// @[fpga/src/main/scala/arty100t/Harness.scala:30:31]
    .clock_uncore              (_dutWrangler_auto_out_0_clock),	// @[fpga/src/main/scala/arty100t/Harness.scala:30:31]
    .clock_tap                 (/* unused */),
    .serial_tl_0_in_ready      (/* unused */),
    .serial_tl_0_in_valid      (1'h0),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:314:9]
    .serial_tl_0_in_bits_phit  (32'h0),
    .serial_tl_0_out_ready     (1'h0),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:314:9]
    .serial_tl_0_out_valid     (/* unused */),
    .serial_tl_0_out_bits_phit (/* unused */),
    .serial_tl_0_clock_in      (1'h0)	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:314:9]
  );	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:100:40]
  plusarg_reader_Arty100THarness_UNIQUIFIED #(
    .DEFAULT(0),
    .FORMAT("custom_boot_pin=%d"),
    .WIDTH(1)
  ) plusarg_reader(	// @[generators/rocket-chip/src/main/scala/util/PlusArg.scala:80:11]
    .out (_plusarg_reader_out)
  );	// @[generators/rocket-chip/src/main/scala/util/PlusArg.scala:80:11]
  ResetCatchAndSync_d3_Arty100THarness_UNIQUIFIED harnessBinderReset_catcher(	// @[generators/rocket-chip/src/main/scala/util/ResetCatchAndSync.scala:39:28]
    .clock         (_dutWrangler_auto_out_0_clock),	// @[fpga/src/main/scala/arty100t/Harness.scala:30:31]
    .reset         (_dutWrangler_auto_out_0_reset),	// @[fpga/src/main/scala/arty100t/Harness.scala:30:31]
    .io_sync_reset (_harnessBinderReset_catcher_io_sync_reset)
  );	// @[generators/rocket-chip/src/main/scala/util/ResetCatchAndSync.scala:39:28]
  assign led_0 = REG_1 == 2'h0;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:314:9, fpga/src/main/scala/arty100t/Harness.scala:62:23, :63:60]
  assign led_1 = REG_1 == 2'h1;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:314:9, fpga/src/main/scala/arty100t/Harness.scala:62:23, :63:60]
  assign led_2 = _GEN;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:314:9, fpga/src/main/scala/arty100t/Harness.scala:63:60]
  assign led_3 = _reset_ibuf_O;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:314:9, :320:28]
  assign led_5 = 1'h0;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:314:9]
  assign led_6 = 1'h0;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:314:9]
  assign led_7 = 1'h0;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:314:9]
  assign led_8 = 1'h0;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:314:9]
  assign led_9 = _mig_io_port_init_calib_complete;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:239:23, :314:9]
  assign led_10 = 1'h0;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:314:9]
  assign led_11 = 1'h0;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:314:9]
  assign led_12 = _chiptop0_uart_tsi_tsi2tl_state[0];	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:314:9, fpga/src/main/scala/arty100t/HarnessBinders.scala:37:46, generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:100:40]
  assign led_13 = _chiptop0_uart_tsi_tsi2tl_state[1];	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:314:9, fpga/src/main/scala/arty100t/HarnessBinders.scala:38:47, generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:100:40]
  assign led_14 = _chiptop0_uart_tsi_tsi2tl_state[2];	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:314:9, fpga/src/main/scala/arty100t/HarnessBinders.scala:39:47, generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:100:40]
  assign led_15 = _chiptop0_uart_tsi_tsi2tl_state[3];	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/Arty100TShell.scala:314:9, fpga/src/main/scala/arty100t/HarnessBinders.scala:40:47, generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:100:40]
endmodule

