// Generated by CIRCT unknown git version
module TLInterconnectCoupler_pbus_to_qavidma(	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:135:7]
  input         clock,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:135:7]
  input         reset,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:135:7]
  output        auto_tl_in_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_tl_in_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_tl_in_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_tl_in_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [6:0]  auto_tl_in_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [30:0] auto_tl_in_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [7:0]  auto_tl_in_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [63:0] auto_tl_in_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_tl_in_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_tl_in_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_tl_in_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_tl_in_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [6:0]  auto_tl_in_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [63:0] auto_tl_in_d_bits_data	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
);

  wire        _fragmenter_auto_anon_out_a_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
  wire [2:0]  _fragmenter_auto_anon_out_a_bits_opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
  wire [1:0]  _fragmenter_auto_anon_out_a_bits_size;	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
  wire [10:0] _fragmenter_auto_anon_out_a_bits_source;	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
  wire [30:0] _fragmenter_auto_anon_out_a_bits_address;	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
  wire [7:0]  _fragmenter_auto_anon_out_a_bits_mask;	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
  wire [63:0] _fragmenter_auto_anon_out_a_bits_data;	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
  wire        _fragmenter_auto_anon_out_d_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
  wire        _dma_auto_in_a_ready;	// @[generators/chipyard/src/main/scala/example/QaviDMA.scala:140:28]
  wire        _dma_auto_in_d_valid;	// @[generators/chipyard/src/main/scala/example/QaviDMA.scala:140:28]
  wire [2:0]  _dma_auto_in_d_bits_opcode;	// @[generators/chipyard/src/main/scala/example/QaviDMA.scala:140:28]
  wire [1:0]  _dma_auto_in_d_bits_size;	// @[generators/chipyard/src/main/scala/example/QaviDMA.scala:140:28]
  wire [10:0] _dma_auto_in_d_bits_source;	// @[generators/chipyard/src/main/scala/example/QaviDMA.scala:140:28]
  wire [63:0] _dma_auto_in_d_bits_data;	// @[generators/chipyard/src/main/scala/example/QaviDMA.scala:140:28]
  QaviDMA dma (	// @[generators/chipyard/src/main/scala/example/QaviDMA.scala:140:28]
    .clock                  (clock),
    .reset                  (reset),
    .auto_in_a_ready        (_dma_auto_in_a_ready),
    .auto_in_a_valid        (_fragmenter_auto_anon_out_a_valid),	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
    .auto_in_a_bits_opcode  (_fragmenter_auto_anon_out_a_bits_opcode),	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
    .auto_in_a_bits_size    (_fragmenter_auto_anon_out_a_bits_size),	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
    .auto_in_a_bits_source  (_fragmenter_auto_anon_out_a_bits_source),	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
    .auto_in_a_bits_address (_fragmenter_auto_anon_out_a_bits_address),	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
    .auto_in_a_bits_mask    (_fragmenter_auto_anon_out_a_bits_mask),	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
    .auto_in_a_bits_data    (_fragmenter_auto_anon_out_a_bits_data),	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
    .auto_in_d_ready        (_fragmenter_auto_anon_out_d_ready),	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
    .auto_in_d_valid        (_dma_auto_in_d_valid),
    .auto_in_d_bits_opcode  (_dma_auto_in_d_bits_opcode),
    .auto_in_d_bits_size    (_dma_auto_in_d_bits_size),
    .auto_in_d_bits_source  (_dma_auto_in_d_bits_source),
    .auto_in_d_bits_data    (_dma_auto_in_d_bits_data)
  );	// @[generators/chipyard/src/main/scala/example/QaviDMA.scala:140:28]
  TLFragmenter fragmenter (	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
    .clock                        (clock),
    .reset                        (reset),
    .auto_anon_in_a_ready         (auto_tl_in_a_ready),
    .auto_anon_in_a_valid         (auto_tl_in_a_valid),
    .auto_anon_in_a_bits_opcode   (auto_tl_in_a_bits_opcode),
    .auto_anon_in_a_bits_size     (auto_tl_in_a_bits_size),
    .auto_anon_in_a_bits_source   (auto_tl_in_a_bits_source),
    .auto_anon_in_a_bits_address  (auto_tl_in_a_bits_address),
    .auto_anon_in_a_bits_mask     (auto_tl_in_a_bits_mask),
    .auto_anon_in_a_bits_data     (auto_tl_in_a_bits_data),
    .auto_anon_in_d_ready         (auto_tl_in_d_ready),
    .auto_anon_in_d_valid         (auto_tl_in_d_valid),
    .auto_anon_in_d_bits_opcode   (auto_tl_in_d_bits_opcode),
    .auto_anon_in_d_bits_size     (auto_tl_in_d_bits_size),
    .auto_anon_in_d_bits_source   (auto_tl_in_d_bits_source),
    .auto_anon_in_d_bits_data     (auto_tl_in_d_bits_data),
    .auto_anon_out_a_ready        (_dma_auto_in_a_ready),	// @[generators/chipyard/src/main/scala/example/QaviDMA.scala:140:28]
    .auto_anon_out_a_valid        (_fragmenter_auto_anon_out_a_valid),
    .auto_anon_out_a_bits_opcode  (_fragmenter_auto_anon_out_a_bits_opcode),
    .auto_anon_out_a_bits_size    (_fragmenter_auto_anon_out_a_bits_size),
    .auto_anon_out_a_bits_source  (_fragmenter_auto_anon_out_a_bits_source),
    .auto_anon_out_a_bits_address (_fragmenter_auto_anon_out_a_bits_address),
    .auto_anon_out_a_bits_mask    (_fragmenter_auto_anon_out_a_bits_mask),
    .auto_anon_out_a_bits_data    (_fragmenter_auto_anon_out_a_bits_data),
    .auto_anon_out_d_ready        (_fragmenter_auto_anon_out_d_ready),
    .auto_anon_out_d_valid        (_dma_auto_in_d_valid),	// @[generators/chipyard/src/main/scala/example/QaviDMA.scala:140:28]
    .auto_anon_out_d_bits_opcode  (_dma_auto_in_d_bits_opcode),	// @[generators/chipyard/src/main/scala/example/QaviDMA.scala:140:28]
    .auto_anon_out_d_bits_size    (_dma_auto_in_d_bits_size),	// @[generators/chipyard/src/main/scala/example/QaviDMA.scala:140:28]
    .auto_anon_out_d_bits_source  (_dma_auto_in_d_bits_source),	// @[generators/chipyard/src/main/scala/example/QaviDMA.scala:140:28]
    .auto_anon_out_d_bits_data    (_dma_auto_in_d_bits_data)	// @[generators/chipyard/src/main/scala/example/QaviDMA.scala:140:28]
  );	// @[generators/rocket-chip/src/main/scala/tilelink/Fragmenter.scala:345:34]
endmodule

