// Generated by CIRCT unknown git version
module VexiiRiscvTile(	// @[generators/vexiiriscv/src/main/scala/vexiiriscv/VexiiRiscvTile.scala:175:7]
  input         clock,	// @[generators/vexiiriscv/src/main/scala/vexiiriscv/VexiiRiscvTile.scala:175:7]
  input         reset,	// @[generators/vexiiriscv/src/main/scala/vexiiriscv/VexiiRiscvTile.scala:175:7]
  input         auto_buffer_out_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_buffer_out_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_buffer_out_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_buffer_out_a_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_buffer_out_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_buffer_out_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [31:0] auto_buffer_out_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [7:0]  auto_buffer_out_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [63:0] auto_buffer_out_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_buffer_out_a_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_buffer_out_b_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_buffer_out_b_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_buffer_out_b_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [1:0]  auto_buffer_out_b_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]  auto_buffer_out_b_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]  auto_buffer_out_b_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [31:0] auto_buffer_out_b_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [7:0]  auto_buffer_out_b_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [63:0] auto_buffer_out_b_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_buffer_out_b_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_buffer_out_c_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_buffer_out_c_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_buffer_out_c_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_buffer_out_c_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_buffer_out_c_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_buffer_out_c_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [31:0] auto_buffer_out_c_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [63:0] auto_buffer_out_c_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_buffer_out_c_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_buffer_out_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_buffer_out_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_buffer_out_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [1:0]  auto_buffer_out_d_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]  auto_buffer_out_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]  auto_buffer_out_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [1:0]  auto_buffer_out_d_bits_sink,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_buffer_out_d_bits_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [63:0] auto_buffer_out_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_buffer_out_d_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_buffer_out_e_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_buffer_out_e_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [1:0]  auto_buffer_out_e_bits_sink,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_int_local_in_2_0,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_int_local_in_1_0,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_int_local_in_1_1,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_hartid_in	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
);

  wire         _core_mem_node_bus_a_valid;	// @[generators/vexiiriscv/src/main/scala/vexiiriscv/VexiiRiscvTile.scala:179:20]
  wire [2:0]   _core_mem_node_bus_a_payload_opcode;	// @[generators/vexiiriscv/src/main/scala/vexiiriscv/VexiiRiscvTile.scala:179:20]
  wire [2:0]   _core_mem_node_bus_a_payload_param;	// @[generators/vexiiriscv/src/main/scala/vexiiriscv/VexiiRiscvTile.scala:179:20]
  wire [3:0]   _core_mem_node_bus_a_payload_source;	// @[generators/vexiiriscv/src/main/scala/vexiiriscv/VexiiRiscvTile.scala:179:20]
  wire [31:0]  _core_mem_node_bus_a_payload_address;	// @[generators/vexiiriscv/src/main/scala/vexiiriscv/VexiiRiscvTile.scala:179:20]
  wire [2:0]   _core_mem_node_bus_a_payload_size;	// @[generators/vexiiriscv/src/main/scala/vexiiriscv/VexiiRiscvTile.scala:179:20]
  wire [15:0]  _core_mem_node_bus_a_payload_mask;	// @[generators/vexiiriscv/src/main/scala/vexiiriscv/VexiiRiscvTile.scala:179:20]
  wire [127:0] _core_mem_node_bus_a_payload_data;	// @[generators/vexiiriscv/src/main/scala/vexiiriscv/VexiiRiscvTile.scala:179:20]
  wire         _core_mem_node_bus_a_payload_corrupt;	// @[generators/vexiiriscv/src/main/scala/vexiiriscv/VexiiRiscvTile.scala:179:20]
  wire         _core_mem_node_bus_b_ready;	// @[generators/vexiiriscv/src/main/scala/vexiiriscv/VexiiRiscvTile.scala:179:20]
  wire         _core_mem_node_bus_c_valid;	// @[generators/vexiiriscv/src/main/scala/vexiiriscv/VexiiRiscvTile.scala:179:20]
  wire [2:0]   _core_mem_node_bus_c_payload_opcode;	// @[generators/vexiiriscv/src/main/scala/vexiiriscv/VexiiRiscvTile.scala:179:20]
  wire [2:0]   _core_mem_node_bus_c_payload_param;	// @[generators/vexiiriscv/src/main/scala/vexiiriscv/VexiiRiscvTile.scala:179:20]
  wire [3:0]   _core_mem_node_bus_c_payload_source;	// @[generators/vexiiriscv/src/main/scala/vexiiriscv/VexiiRiscvTile.scala:179:20]
  wire [31:0]  _core_mem_node_bus_c_payload_address;	// @[generators/vexiiriscv/src/main/scala/vexiiriscv/VexiiRiscvTile.scala:179:20]
  wire [2:0]   _core_mem_node_bus_c_payload_size;	// @[generators/vexiiriscv/src/main/scala/vexiiriscv/VexiiRiscvTile.scala:179:20]
  wire [127:0] _core_mem_node_bus_c_payload_data;	// @[generators/vexiiriscv/src/main/scala/vexiiriscv/VexiiRiscvTile.scala:179:20]
  wire         _core_mem_node_bus_c_payload_corrupt;	// @[generators/vexiiriscv/src/main/scala/vexiiriscv/VexiiRiscvTile.scala:179:20]
  wire         _core_mem_node_bus_d_ready;	// @[generators/vexiiriscv/src/main/scala/vexiiriscv/VexiiRiscvTile.scala:179:20]
  wire         _core_mem_node_bus_e_valid;	// @[generators/vexiiriscv/src/main/scala/vexiiriscv/VexiiRiscvTile.scala:179:20]
  wire [3:0]   _core_mem_node_bus_e_payload_sink;	// @[generators/vexiiriscv/src/main/scala/vexiiriscv/VexiiRiscvTile.scala:179:20]
  wire         _widget_auto_anon_in_a_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
  wire         _widget_auto_anon_in_b_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
  wire [2:0]   _widget_auto_anon_in_b_bits_opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
  wire [1:0]   _widget_auto_anon_in_b_bits_param;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
  wire [3:0]   _widget_auto_anon_in_b_bits_size;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
  wire [3:0]   _widget_auto_anon_in_b_bits_source;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
  wire [31:0]  _widget_auto_anon_in_b_bits_address;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
  wire         _widget_auto_anon_in_c_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
  wire         _widget_auto_anon_in_d_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
  wire [2:0]   _widget_auto_anon_in_d_bits_opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
  wire [1:0]   _widget_auto_anon_in_d_bits_param;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
  wire [3:0]   _widget_auto_anon_in_d_bits_size;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
  wire [3:0]   _widget_auto_anon_in_d_bits_source;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
  wire [1:0]   _widget_auto_anon_in_d_bits_sink;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
  wire         _widget_auto_anon_in_d_bits_denied;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
  wire [127:0] _widget_auto_anon_in_d_bits_data;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
  wire         _widget_auto_anon_in_d_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
  wire         _widget_auto_anon_in_e_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
  wire         _widget_auto_anon_out_a_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
  wire [2:0]   _widget_auto_anon_out_a_bits_opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
  wire [2:0]   _widget_auto_anon_out_a_bits_param;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
  wire [3:0]   _widget_auto_anon_out_a_bits_size;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
  wire [3:0]   _widget_auto_anon_out_a_bits_source;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
  wire [31:0]  _widget_auto_anon_out_a_bits_address;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
  wire [7:0]   _widget_auto_anon_out_a_bits_mask;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
  wire [63:0]  _widget_auto_anon_out_a_bits_data;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
  wire         _widget_auto_anon_out_a_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
  wire         _widget_auto_anon_out_b_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
  wire         _widget_auto_anon_out_c_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
  wire [2:0]   _widget_auto_anon_out_c_bits_opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
  wire [2:0]   _widget_auto_anon_out_c_bits_param;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
  wire [3:0]   _widget_auto_anon_out_c_bits_size;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
  wire [3:0]   _widget_auto_anon_out_c_bits_source;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
  wire [31:0]  _widget_auto_anon_out_c_bits_address;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
  wire [63:0]  _widget_auto_anon_out_c_bits_data;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
  wire         _widget_auto_anon_out_c_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
  wire         _widget_auto_anon_out_d_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
  wire         _widget_auto_anon_out_e_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
  wire [1:0]   _widget_auto_anon_out_e_bits_sink;	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
  wire         _buffer_auto_in_a_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire         _buffer_auto_in_b_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire [2:0]   _buffer_auto_in_b_bits_opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire [1:0]   _buffer_auto_in_b_bits_param;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire [3:0]   _buffer_auto_in_b_bits_size;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire [3:0]   _buffer_auto_in_b_bits_source;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire [31:0]  _buffer_auto_in_b_bits_address;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire         _buffer_auto_in_c_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire         _buffer_auto_in_d_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire [2:0]   _buffer_auto_in_d_bits_opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire [1:0]   _buffer_auto_in_d_bits_param;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire [3:0]   _buffer_auto_in_d_bits_size;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire [3:0]   _buffer_auto_in_d_bits_source;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire [1:0]   _buffer_auto_in_d_bits_sink;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire         _buffer_auto_in_d_bits_denied;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire [63:0]  _buffer_auto_in_d_bits_data;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire         _buffer_auto_in_d_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire         _buffer_auto_in_e_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire         _intXbar_auto_anon_out_1;	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:57:37]
  wire         _intXbar_auto_anon_out_2;	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:57:37]
  wire         _intXbar_auto_anon_out_3;	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:57:37]
  IntXbar_i4_o1 intXbar (	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:57:37]
    .auto_anon_in_2_0 (auto_int_local_in_2_0),
    .auto_anon_in_1_0 (auto_int_local_in_1_0),
    .auto_anon_in_1_1 (auto_int_local_in_1_1),
    .auto_anon_out_1  (_intXbar_auto_anon_out_1),
    .auto_anon_out_2  (_intXbar_auto_anon_out_2),
    .auto_anon_out_3  (_intXbar_auto_anon_out_3)
  );	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:57:37]
  TLBuffer_a32d64s4k2z4c buffer (	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
    .clock                   (clock),
    .reset                   (reset),
    .auto_in_a_ready         (_buffer_auto_in_a_ready),
    .auto_in_a_valid         (_widget_auto_anon_out_a_valid),	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
    .auto_in_a_bits_opcode   (_widget_auto_anon_out_a_bits_opcode),	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
    .auto_in_a_bits_param    (_widget_auto_anon_out_a_bits_param),	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
    .auto_in_a_bits_size     (_widget_auto_anon_out_a_bits_size),	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
    .auto_in_a_bits_source   (_widget_auto_anon_out_a_bits_source),	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
    .auto_in_a_bits_address  (_widget_auto_anon_out_a_bits_address),	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
    .auto_in_a_bits_mask     (_widget_auto_anon_out_a_bits_mask),	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
    .auto_in_a_bits_data     (_widget_auto_anon_out_a_bits_data),	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
    .auto_in_a_bits_corrupt  (_widget_auto_anon_out_a_bits_corrupt),	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
    .auto_in_b_ready         (_widget_auto_anon_out_b_ready),	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
    .auto_in_b_valid         (_buffer_auto_in_b_valid),
    .auto_in_b_bits_opcode   (_buffer_auto_in_b_bits_opcode),
    .auto_in_b_bits_param    (_buffer_auto_in_b_bits_param),
    .auto_in_b_bits_size     (_buffer_auto_in_b_bits_size),
    .auto_in_b_bits_source   (_buffer_auto_in_b_bits_source),
    .auto_in_b_bits_address  (_buffer_auto_in_b_bits_address),
    .auto_in_b_bits_mask     (/* unused */),
    .auto_in_b_bits_data     (/* unused */),
    .auto_in_b_bits_corrupt  (/* unused */),
    .auto_in_c_ready         (_buffer_auto_in_c_ready),
    .auto_in_c_valid         (_widget_auto_anon_out_c_valid),	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
    .auto_in_c_bits_opcode   (_widget_auto_anon_out_c_bits_opcode),	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
    .auto_in_c_bits_param    (_widget_auto_anon_out_c_bits_param),	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
    .auto_in_c_bits_size     (_widget_auto_anon_out_c_bits_size),	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
    .auto_in_c_bits_source   (_widget_auto_anon_out_c_bits_source),	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
    .auto_in_c_bits_address  (_widget_auto_anon_out_c_bits_address),	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
    .auto_in_c_bits_data     (_widget_auto_anon_out_c_bits_data),	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
    .auto_in_c_bits_corrupt  (_widget_auto_anon_out_c_bits_corrupt),	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
    .auto_in_d_ready         (_widget_auto_anon_out_d_ready),	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
    .auto_in_d_valid         (_buffer_auto_in_d_valid),
    .auto_in_d_bits_opcode   (_buffer_auto_in_d_bits_opcode),
    .auto_in_d_bits_param    (_buffer_auto_in_d_bits_param),
    .auto_in_d_bits_size     (_buffer_auto_in_d_bits_size),
    .auto_in_d_bits_source   (_buffer_auto_in_d_bits_source),
    .auto_in_d_bits_sink     (_buffer_auto_in_d_bits_sink),
    .auto_in_d_bits_denied   (_buffer_auto_in_d_bits_denied),
    .auto_in_d_bits_data     (_buffer_auto_in_d_bits_data),
    .auto_in_d_bits_corrupt  (_buffer_auto_in_d_bits_corrupt),
    .auto_in_e_ready         (_buffer_auto_in_e_ready),
    .auto_in_e_valid         (_widget_auto_anon_out_e_valid),	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
    .auto_in_e_bits_sink     (_widget_auto_anon_out_e_bits_sink),	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
    .auto_out_a_ready        (auto_buffer_out_a_ready),
    .auto_out_a_valid        (auto_buffer_out_a_valid),
    .auto_out_a_bits_opcode  (auto_buffer_out_a_bits_opcode),
    .auto_out_a_bits_param   (auto_buffer_out_a_bits_param),
    .auto_out_a_bits_size    (auto_buffer_out_a_bits_size),
    .auto_out_a_bits_source  (auto_buffer_out_a_bits_source),
    .auto_out_a_bits_address (auto_buffer_out_a_bits_address),
    .auto_out_a_bits_mask    (auto_buffer_out_a_bits_mask),
    .auto_out_a_bits_data    (auto_buffer_out_a_bits_data),
    .auto_out_a_bits_corrupt (auto_buffer_out_a_bits_corrupt),
    .auto_out_b_ready        (auto_buffer_out_b_ready),
    .auto_out_b_valid        (auto_buffer_out_b_valid),
    .auto_out_b_bits_opcode  (auto_buffer_out_b_bits_opcode),
    .auto_out_b_bits_param   (auto_buffer_out_b_bits_param),
    .auto_out_b_bits_size    (auto_buffer_out_b_bits_size),
    .auto_out_b_bits_source  (auto_buffer_out_b_bits_source),
    .auto_out_b_bits_address (auto_buffer_out_b_bits_address),
    .auto_out_b_bits_mask    (auto_buffer_out_b_bits_mask),
    .auto_out_b_bits_data    (auto_buffer_out_b_bits_data),
    .auto_out_b_bits_corrupt (auto_buffer_out_b_bits_corrupt),
    .auto_out_c_ready        (auto_buffer_out_c_ready),
    .auto_out_c_valid        (auto_buffer_out_c_valid),
    .auto_out_c_bits_opcode  (auto_buffer_out_c_bits_opcode),
    .auto_out_c_bits_param   (auto_buffer_out_c_bits_param),
    .auto_out_c_bits_size    (auto_buffer_out_c_bits_size),
    .auto_out_c_bits_source  (auto_buffer_out_c_bits_source),
    .auto_out_c_bits_address (auto_buffer_out_c_bits_address),
    .auto_out_c_bits_data    (auto_buffer_out_c_bits_data),
    .auto_out_c_bits_corrupt (auto_buffer_out_c_bits_corrupt),
    .auto_out_d_ready        (auto_buffer_out_d_ready),
    .auto_out_d_valid        (auto_buffer_out_d_valid),
    .auto_out_d_bits_opcode  (auto_buffer_out_d_bits_opcode),
    .auto_out_d_bits_param   (auto_buffer_out_d_bits_param),
    .auto_out_d_bits_size    (auto_buffer_out_d_bits_size),
    .auto_out_d_bits_source  (auto_buffer_out_d_bits_source),
    .auto_out_d_bits_sink    (auto_buffer_out_d_bits_sink),
    .auto_out_d_bits_denied  (auto_buffer_out_d_bits_denied),
    .auto_out_d_bits_data    (auto_buffer_out_d_bits_data),
    .auto_out_d_bits_corrupt (auto_buffer_out_d_bits_corrupt),
    .auto_out_e_ready        (auto_buffer_out_e_ready),
    .auto_out_e_valid        (auto_buffer_out_e_valid),
    .auto_out_e_bits_sink    (auto_buffer_out_e_bits_sink)
  );	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  TLWidthWidget16 widget (	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
    .clock                        (clock),
    .reset                        (reset),
    .auto_anon_in_a_ready         (_widget_auto_anon_in_a_ready),
    .auto_anon_in_a_valid         (_core_mem_node_bus_a_valid),	// @[generators/vexiiriscv/src/main/scala/vexiiriscv/VexiiRiscvTile.scala:179:20]
    .auto_anon_in_a_bits_opcode   (_core_mem_node_bus_a_payload_opcode),	// @[generators/vexiiriscv/src/main/scala/vexiiriscv/VexiiRiscvTile.scala:179:20]
    .auto_anon_in_a_bits_param    (_core_mem_node_bus_a_payload_param),	// @[generators/vexiiriscv/src/main/scala/vexiiriscv/VexiiRiscvTile.scala:179:20]
    .auto_anon_in_a_bits_size     ({1'h0, _core_mem_node_bus_a_payload_size}),	// @[generators/vexiiriscv/src/main/scala/vexiiriscv/VexiiRiscvTile.scala:179:20, :205:18]
    .auto_anon_in_a_bits_source   (_core_mem_node_bus_a_payload_source),	// @[generators/vexiiriscv/src/main/scala/vexiiriscv/VexiiRiscvTile.scala:179:20]
    .auto_anon_in_a_bits_address  (_core_mem_node_bus_a_payload_address),	// @[generators/vexiiriscv/src/main/scala/vexiiriscv/VexiiRiscvTile.scala:179:20]
    .auto_anon_in_a_bits_mask     (_core_mem_node_bus_a_payload_opcode == 3'h6 | (&_core_mem_node_bus_a_payload_opcode) ? 16'hFFFF : _core_mem_node_bus_a_payload_mask),	// @[generators/rocket-chip/src/main/scala/util/package.scala:16:47, :81:59, generators/vexiiriscv/src/main/scala/vexiiriscv/VexiiRiscvTile.scala:179:20, :206:18, :207:106, :208:20]
    .auto_anon_in_a_bits_data     (_core_mem_node_bus_a_payload_data),	// @[generators/vexiiriscv/src/main/scala/vexiiriscv/VexiiRiscvTile.scala:179:20]
    .auto_anon_in_a_bits_corrupt  (_core_mem_node_bus_a_payload_corrupt),	// @[generators/vexiiriscv/src/main/scala/vexiiriscv/VexiiRiscvTile.scala:179:20]
    .auto_anon_in_b_ready         (_core_mem_node_bus_b_ready),	// @[generators/vexiiriscv/src/main/scala/vexiiriscv/VexiiRiscvTile.scala:179:20]
    .auto_anon_in_b_valid         (_widget_auto_anon_in_b_valid),
    .auto_anon_in_b_bits_opcode   (_widget_auto_anon_in_b_bits_opcode),
    .auto_anon_in_b_bits_param    (_widget_auto_anon_in_b_bits_param),
    .auto_anon_in_b_bits_size     (_widget_auto_anon_in_b_bits_size),
    .auto_anon_in_b_bits_source   (_widget_auto_anon_in_b_bits_source),
    .auto_anon_in_b_bits_address  (_widget_auto_anon_in_b_bits_address),
    .auto_anon_in_c_ready         (_widget_auto_anon_in_c_ready),
    .auto_anon_in_c_valid         (_core_mem_node_bus_c_valid),	// @[generators/vexiiriscv/src/main/scala/vexiiriscv/VexiiRiscvTile.scala:179:20]
    .auto_anon_in_c_bits_opcode   (_core_mem_node_bus_c_payload_opcode),	// @[generators/vexiiriscv/src/main/scala/vexiiriscv/VexiiRiscvTile.scala:179:20]
    .auto_anon_in_c_bits_param    (_core_mem_node_bus_c_payload_param),	// @[generators/vexiiriscv/src/main/scala/vexiiriscv/VexiiRiscvTile.scala:179:20]
    .auto_anon_in_c_bits_size     ({1'h0, _core_mem_node_bus_c_payload_size}),	// @[generators/vexiiriscv/src/main/scala/vexiiriscv/VexiiRiscvTile.scala:179:20, :227:18]
    .auto_anon_in_c_bits_source   (_core_mem_node_bus_c_payload_source),	// @[generators/vexiiriscv/src/main/scala/vexiiriscv/VexiiRiscvTile.scala:179:20]
    .auto_anon_in_c_bits_address  (_core_mem_node_bus_c_payload_address & 32'hFFFFFFC0),	// @[generators/vexiiriscv/src/main/scala/vexiiriscv/VexiiRiscvTile.scala:179:20, :226:63]
    .auto_anon_in_c_bits_data     (_core_mem_node_bus_c_payload_data),	// @[generators/vexiiriscv/src/main/scala/vexiiriscv/VexiiRiscvTile.scala:179:20]
    .auto_anon_in_c_bits_corrupt  (_core_mem_node_bus_c_payload_corrupt),	// @[generators/vexiiriscv/src/main/scala/vexiiriscv/VexiiRiscvTile.scala:179:20]
    .auto_anon_in_d_ready         (_core_mem_node_bus_d_ready),	// @[generators/vexiiriscv/src/main/scala/vexiiriscv/VexiiRiscvTile.scala:179:20]
    .auto_anon_in_d_valid         (_widget_auto_anon_in_d_valid),
    .auto_anon_in_d_bits_opcode   (_widget_auto_anon_in_d_bits_opcode),
    .auto_anon_in_d_bits_param    (_widget_auto_anon_in_d_bits_param),
    .auto_anon_in_d_bits_size     (_widget_auto_anon_in_d_bits_size),
    .auto_anon_in_d_bits_source   (_widget_auto_anon_in_d_bits_source),
    .auto_anon_in_d_bits_sink     (_widget_auto_anon_in_d_bits_sink),
    .auto_anon_in_d_bits_denied   (_widget_auto_anon_in_d_bits_denied),
    .auto_anon_in_d_bits_data     (_widget_auto_anon_in_d_bits_data),
    .auto_anon_in_d_bits_corrupt  (_widget_auto_anon_in_d_bits_corrupt),
    .auto_anon_in_e_ready         (_widget_auto_anon_in_e_ready),
    .auto_anon_in_e_valid         (_core_mem_node_bus_e_valid),	// @[generators/vexiiriscv/src/main/scala/vexiiriscv/VexiiRiscvTile.scala:179:20]
    .auto_anon_in_e_bits_sink     (_core_mem_node_bus_e_payload_sink[1:0]),	// @[generators/vexiiriscv/src/main/scala/vexiiriscv/VexiiRiscvTile.scala:179:20, :244:18]
    .auto_anon_out_a_ready        (_buffer_auto_in_a_ready),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
    .auto_anon_out_a_valid        (_widget_auto_anon_out_a_valid),
    .auto_anon_out_a_bits_opcode  (_widget_auto_anon_out_a_bits_opcode),
    .auto_anon_out_a_bits_param   (_widget_auto_anon_out_a_bits_param),
    .auto_anon_out_a_bits_size    (_widget_auto_anon_out_a_bits_size),
    .auto_anon_out_a_bits_source  (_widget_auto_anon_out_a_bits_source),
    .auto_anon_out_a_bits_address (_widget_auto_anon_out_a_bits_address),
    .auto_anon_out_a_bits_mask    (_widget_auto_anon_out_a_bits_mask),
    .auto_anon_out_a_bits_data    (_widget_auto_anon_out_a_bits_data),
    .auto_anon_out_a_bits_corrupt (_widget_auto_anon_out_a_bits_corrupt),
    .auto_anon_out_b_ready        (_widget_auto_anon_out_b_ready),
    .auto_anon_out_b_valid        (_buffer_auto_in_b_valid),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
    .auto_anon_out_b_bits_opcode  (_buffer_auto_in_b_bits_opcode),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
    .auto_anon_out_b_bits_param   (_buffer_auto_in_b_bits_param),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
    .auto_anon_out_b_bits_size    (_buffer_auto_in_b_bits_size),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
    .auto_anon_out_b_bits_source  (_buffer_auto_in_b_bits_source),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
    .auto_anon_out_b_bits_address (_buffer_auto_in_b_bits_address),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
    .auto_anon_out_c_ready        (_buffer_auto_in_c_ready),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
    .auto_anon_out_c_valid        (_widget_auto_anon_out_c_valid),
    .auto_anon_out_c_bits_opcode  (_widget_auto_anon_out_c_bits_opcode),
    .auto_anon_out_c_bits_param   (_widget_auto_anon_out_c_bits_param),
    .auto_anon_out_c_bits_size    (_widget_auto_anon_out_c_bits_size),
    .auto_anon_out_c_bits_source  (_widget_auto_anon_out_c_bits_source),
    .auto_anon_out_c_bits_address (_widget_auto_anon_out_c_bits_address),
    .auto_anon_out_c_bits_data    (_widget_auto_anon_out_c_bits_data),
    .auto_anon_out_c_bits_corrupt (_widget_auto_anon_out_c_bits_corrupt),
    .auto_anon_out_d_ready        (_widget_auto_anon_out_d_ready),
    .auto_anon_out_d_valid        (_buffer_auto_in_d_valid),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
    .auto_anon_out_d_bits_opcode  (_buffer_auto_in_d_bits_opcode),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
    .auto_anon_out_d_bits_param   (_buffer_auto_in_d_bits_param),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
    .auto_anon_out_d_bits_size    (_buffer_auto_in_d_bits_size),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
    .auto_anon_out_d_bits_source  (_buffer_auto_in_d_bits_source),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
    .auto_anon_out_d_bits_sink    (_buffer_auto_in_d_bits_sink),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
    .auto_anon_out_d_bits_denied  (_buffer_auto_in_d_bits_denied),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
    .auto_anon_out_d_bits_data    (_buffer_auto_in_d_bits_data),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
    .auto_anon_out_d_bits_corrupt (_buffer_auto_in_d_bits_corrupt),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
    .auto_anon_out_e_ready        (_buffer_auto_in_e_ready),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
    .auto_anon_out_e_valid        (_widget_auto_anon_out_e_valid),
    .auto_anon_out_e_bits_sink    (_widget_auto_anon_out_e_bits_sink)
  );	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
  VexiiRiscvTilelink core (	// @[generators/vexiiriscv/src/main/scala/vexiiriscv/VexiiRiscvTile.scala:179:20]
    .clk                            (clock),
    .reset                          (reset),
    .hartId                         ({31'h0, auto_hartid_in}),	// @[generators/vexiiriscv/src/main/scala/vexiiriscv/VexiiRiscvTile.scala:188:18]
    .mti_flag                       (_intXbar_auto_anon_out_2),	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:57:37]
    .msi_flag                       (_intXbar_auto_anon_out_1),	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:57:37]
    .mei_flag                       (_intXbar_auto_anon_out_3),	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:57:37]
    .sei_flag                       (1'h0),
    .mem_node_bus_a_valid           (_core_mem_node_bus_a_valid),
    .mem_node_bus_a_ready           (_widget_auto_anon_in_a_ready),	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
    .mem_node_bus_a_payload_opcode  (_core_mem_node_bus_a_payload_opcode),
    .mem_node_bus_a_payload_param   (_core_mem_node_bus_a_payload_param),
    .mem_node_bus_a_payload_source  (_core_mem_node_bus_a_payload_source),
    .mem_node_bus_a_payload_address (_core_mem_node_bus_a_payload_address),
    .mem_node_bus_a_payload_size    (_core_mem_node_bus_a_payload_size),
    .mem_node_bus_a_payload_mask    (_core_mem_node_bus_a_payload_mask),
    .mem_node_bus_a_payload_data    (_core_mem_node_bus_a_payload_data),
    .mem_node_bus_a_payload_corrupt (_core_mem_node_bus_a_payload_corrupt),
    .mem_node_bus_b_valid           (_widget_auto_anon_in_b_valid),	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
    .mem_node_bus_b_ready           (_core_mem_node_bus_b_ready),
    .mem_node_bus_b_payload_opcode  (_widget_auto_anon_in_b_bits_opcode),	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
    .mem_node_bus_b_payload_param   ({1'h0, _widget_auto_anon_in_b_bits_param}),	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28, generators/vexiiriscv/src/main/scala/vexiiriscv/VexiiRiscvTile.scala:216:40]
    .mem_node_bus_b_payload_source  (_widget_auto_anon_in_b_bits_source),	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
    .mem_node_bus_b_payload_address (_widget_auto_anon_in_b_bits_address),	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
    .mem_node_bus_b_payload_size    (_widget_auto_anon_in_b_bits_size[2:0]),	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28, generators/vexiiriscv/src/main/scala/vexiiriscv/VexiiRiscvTile.scala:219:39]
    .mem_node_bus_c_valid           (_core_mem_node_bus_c_valid),
    .mem_node_bus_c_ready           (_widget_auto_anon_in_c_ready),	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
    .mem_node_bus_c_payload_opcode  (_core_mem_node_bus_c_payload_opcode),
    .mem_node_bus_c_payload_param   (_core_mem_node_bus_c_payload_param),
    .mem_node_bus_c_payload_source  (_core_mem_node_bus_c_payload_source),
    .mem_node_bus_c_payload_address (_core_mem_node_bus_c_payload_address),
    .mem_node_bus_c_payload_size    (_core_mem_node_bus_c_payload_size),
    .mem_node_bus_c_payload_data    (_core_mem_node_bus_c_payload_data),
    .mem_node_bus_c_payload_corrupt (_core_mem_node_bus_c_payload_corrupt),
    .mem_node_bus_d_valid           (_widget_auto_anon_in_d_valid),	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
    .mem_node_bus_d_ready           (_core_mem_node_bus_d_ready),
    .mem_node_bus_d_payload_opcode  (_widget_auto_anon_in_d_bits_opcode),	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
    .mem_node_bus_d_payload_param   ({1'h0, _widget_auto_anon_in_d_bits_param}),	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28, generators/vexiiriscv/src/main/scala/vexiiriscv/VexiiRiscvTile.scala:234:40]
    .mem_node_bus_d_payload_source  (_widget_auto_anon_in_d_bits_source),	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
    .mem_node_bus_d_payload_size    (_widget_auto_anon_in_d_bits_size[2:0]),	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28, generators/vexiiriscv/src/main/scala/vexiiriscv/VexiiRiscvTile.scala:236:39]
    .mem_node_bus_d_payload_data    (_widget_auto_anon_in_d_bits_data),	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
    .mem_node_bus_d_payload_corrupt (_widget_auto_anon_in_d_bits_corrupt),	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
    .mem_node_bus_d_payload_denied  (_widget_auto_anon_in_d_bits_denied),	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
    .mem_node_bus_d_payload_sink    ({2'h0, _widget_auto_anon_in_d_bits_sink}),	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28, generators/vexiiriscv/src/main/scala/vexiiriscv/VexiiRiscvTile.scala:240:39]
    .mem_node_bus_e_valid           (_core_mem_node_bus_e_valid),
    .mem_node_bus_e_ready           (_widget_auto_anon_in_e_ready),	// @[generators/rocket-chip/src/main/scala/tilelink/WidthWidget.scala:230:28]
    .mem_node_bus_e_payload_sink    (_core_mem_node_bus_e_payload_sink)
  );	// @[generators/vexiiriscv/src/main/scala/vexiiriscv/VexiiRiscvTile.scala:179:20]
endmodule

